### ISSUE TITLE
/opt/strands/strands_catkin_ws/src/strands_utils/mongodb_store/ does not exist

### ISSUE THREAD

**Issue by ferdianjovan** [strands-project/strands_utils#110]
Hi all, 
I tried to follow the instruction in https://github.com/strands-project/strands_utils/tree/hydro-devel/strands_tweets to set up twitter for Bob. However, I could not find any mongodb_store inside strands_utils.

Is mongodb_store meant by the instruction in mongodb_store (/mongodb_store/mongodb_store)?

Also, Is there any example how to create the twitter_params.yaml?

Thanks.

**Comment by hawesie** [comment]
File is now here https://github.com/strands-project/strands_deployment/blob/master/strands_parameters/defaults/twitter_params.yaml

**Comment by cdondrup** [comment]
Apparently the README is out of date. Would you mind updating it @ferdianjovan as you are setting it up atm and should know how it works afterwards?

**Comment by ferdianjovan** [comment]
Ok, I will later in this day.

**Comment by cdondrup** [comment]
Thank you.
