### ISSUE TITLE
[qr_read_and_tweet] Remove hard coded overlay image path in image_branding.py

### ISSUE THREAD

**Issue by cburbridge** [strands-project/strands_utils#112]
Maybe also add some options about how to overlay the image, not just add it.

**Comment by Jailander** [comment]
I will take a look into this, I had plans to add parameters for the image size of the image that will be tweeted and maybe changing the colour of the branding. I also thought about creating a mode that brand the image with some text instead of an image because that maybe useful. Did you have anything more specific in mind?

**Comment by cburbridge** [comment]
Sounds good. At the moment the code adds the rgb of the overlay to the RGB of the image:
`output_image = input_image + 0.7 overlay`. I was thinking maybe add an option to use the transparency channel of the PNG to allow overlaying as a replacement:
`output_image = input_image if overlay is transparent else overlay`
This way, it would be possible to overlay something on top of white backgrounds, and colours wont be diluted by the background.

Would it be better as a service rather than action? We could also add an option to process image streams continuously.

**Comment by Jailander** [comment]
Overlaying the images sounds fine there should be no problem with it, about the service, maybe I can do both like the tweeter node that has an action server and service

**Comment by hawesie** [comment]
As overlaying shouldn't take long, I think a service will suffice. Actions are only really necessary for longer running things that may need to be preempted.

**Comment by Jailander** [comment]
OK, I'll finish it today in the afternoon

**Comment by Jailander** [comment]
we should close this issue as this is no longer the correct repo and the issue has been copied to https://github.com/strands-project/strands_utils/issues/112
