### ISSUE TITLE
[qr_read_and_tweet] Performance issues

### ISSUE THREAD

**Issue by hawesie** [strands-project/strands_utils#113]
The qr read and tweet stuff takes an age to trigger in the NHM system (or at least it appears to). Is there any way to speed this up?

**Comment by Jailander** [comment]
yes that was a problem we faced in the nhm, I tried many things but no success, we had in our plans to use @gestom 's circle detection for that but haven't done it yet

**Comment by Jailander** [comment]
I think we should close this issue as it is now referenced in https://github.com/strands-project/strands_social/issues/7
