### ISSUE TITLE
[previous_position_service] to strands_navigation?

### ISSUE THREAD

**Issue by marc-hanheide** [strands-project/strands_utils#123]
This appears to be fitting strands_navigation. Is it even worth this being a separate package or should it be just one script in one of the strands_navigation packages?

Currently, this is the only dependency that strands_navigation still has with strands_utils, hence it would be good to move it soon.

**Comment by nilsbore** [comment]
Yes, I think this should be moved to the backtrack_behaviour package that's supposed to be in the recovery behaviour repo (or similar) of strands_navigation. @BFALacerda How should we organize the recovery behaviours?

**Comment by nilsbore** [comment]
Also, `republish_pointcloud_service` should be moved there.

**Comment by bfalacerda** [comment]
my local organization is a metapackage called strands_recovery_behaviours where I have:
1. the (still being developed) smach recovery and monitor behaviours to be added to the (scitos-independent) monitored_navigation state machine that will remain in strands_navigation in one package
2. Backtrack recovery package that you implemented in https://github.com/strands-project/strands_navigation/pull/64 in another. I can also put this there.
   
   If we go with this solution, we need to create a new repo called strands_recovery_behaviours, which will be dependent on a lot of scitos specific stuff, freeing strands_navigation from all those dependencies. @marc-hanheide ?

**Comment by marc-hanheide** [comment]
What dependencies are we talking about, @BFALacerda ? It sounds like a reasonable plan, just want to make sure.

**Comment by bfalacerda** [comment]
E.g. by  copy/paste of a couple of recovery behaviour python scripts:

```
from scitos_msgs.msg import MotorStatus
from scitos_msgs.srv import ResetMotorStop
from scitos_msgs.srv import EnableMotors
```

The smach implementations of our scitos-specific recovery behaviours (recover_bumper, stuck on carpet) go to the strands_recovery_behaviours repo, along with the republish_pointcloud_service and the previous_position_service.

**Comment by hawesie** [comment]
:+1:

**Comment by marc-hanheide** [comment]
:+1:

**Comment by bfalacerda** [comment]
@marc-hanheide @hawesie can you create a strands_recovery_behaviours repo for me to put this in?

**Comment by marc-hanheide** [comment]
done: https://github.com/strands-project/strands_recovery_behaviours

**Comment by bfalacerda** [comment]
thanks

**Comment by bfalacerda** [comment]
this was merged into the backtrack_behaviour package by @nilsbore , and the rest of the discussion is also pretty much finished
