### ISSUE TITLE
remove laser_door_check

### ISSUE THREAD

**Issue by Jailander** [strands-project/strands_utils#124]
I think we should remove laser_door_check as it is better implemented in https://github.com/strands-project/strands_apps/tree/hydro-devel/door_pass

**Comment by hawesie** [comment]
The strands_apps version is now released so we should indeed remove laser_door_check

**Comment by Jailander** [comment]
hmmm I already did it but I probably forgot to create the pull request sorry

**Comment by Jailander** [comment]
nope just did it locally will do it tomorrow then

**Comment by hawesie** [comment]
See referenced PRs for what I did in parallel.
