### ISSUE TITLE
release this?

### ISSUE THREAD

**Issue by bfalacerda** [strands-project/strands_utils#138]
Are there plans to release this? I want to use `battery_check`, and noticed that I have to get it cloned in the local workspace.

**Comment by hawesie** [comment]
@marc-hanheide what was the strategy for dealing with this? Are we moving the things to release to strands_apps?

**Comment by marc-hanheide** [comment]
yes, we didn't want to bother to fix this entire repo. But then this is not a releasable module anyway. It's not even a catkin package. It's only a local configuration on the robot. So, I'd say, follow the instructions and install locally.

**Comment by bfalacerda** [comment]
fair enough. I'm closing it then
