### ISSUE TITLE
Does the datacentre_path parameter have to be private?

### ISSUE THREAD

**Issue by Jailander** [strands-project/strands_utils#17]
Hi,

Is there any reason why the datacentre_path parameter is private? I think it would be best to make it a common parameter so it can be accessible by any other node.

This way for example the config server can load the default parameters from the "defaults" folder that can now be located in the strands_datacentre and not in the package directory as it does now (this is a big issue when a new version of strands_utils is pulled from github), this could also be useful when we start adding information to the data centre from any other module.

**Comment by cburbridge** [comment]
It's private as only the mongodb_server.py node requires access to it. It contains the path of the Mongo DB files, which is no use to other nodes.

The parameters in strands_utils/strands_datacentre/defaults are supposed to be on GitHub, and shared between users. They are default values that can be overlayed with local replacement values. Each time the config_manager node is started, it loads default parameters from the defaults/ folder, then local parameters from the db.

The DB files don't live inside github -  each institution has to have their own database.  So when you pull an updated strands_utils package, your own local parameter setting won't be effected.

**Comment by Jailander** [comment]
Ok, now I understand,

I thought default parameters were robot oriented whilst locals were focussed toward specific applications so I couldn't see the point on having the parameters on the defaults/ folder (or in this case keep the files with the parameters).

Thank you

**Comment by marc-hanheide** [comment]
I also have a question on this: The parameter is hard-wired in the launch file datacentre.launch. This is a problem if one would like to run systems in parallel (e.g. on the continuous integration server). Then I'd like to have different database servers running in parallel. Also, we sometimes have students running things in their own workspace. In general, no write access to a STRANDS dir should be _required_ in my view by any launch files.

**Comment by cburbridge** [comment]
I see what you mean, and have issued pull request https://github.com/strands-project/strands_utils/pull/20 to allow this.

**Comment by cburbridge** [comment]
However, if you have two instances of the mongodb_server.py running, there will only be one copy of the parameters datacentre_port and datacentre_host on the parameter server. This means that clients will use the last instance started, which will prevent you from being able to run systems in parallel using the same roscore...

**Comment by marc-hanheide** [comment]
well, of course it's running on different roscore and therefore parameter servers as well.
