### ISSUE TITLE
[strands_datacentre] mongod does not always log to stdout

### ISSUE THREAD

**Issue by hawesie** [strands-project/strands_utils#22]
mongod can have its output parameters set by a global config file. On my system (OS X, Homebrew) it was configured to log to a file not stdout as assumed by mongodb_server.py, meaning that the server didn't get feedback from the db. The server instructions should be updated to make people aware of this, and I suggest adding code to catch this situation happening. When logging to file, the following /is/ printed on stdout:

``` bash
banks:~ nah$ mongod --dbpath /opt/strands/strands_datacentre --port 62345 
all output going to: /usr/local/var/log/mongodb/mongo.log
```

To fix configuration, users need to remain the log\* entries from the config file.

**Comment by cburbridge** [comment]
If you run:

```
mongod --dbpath /opt/strands/strands_datacentre --port 62345 -f /dev/null
```

it should avoid loading a default config file. Please test this, and if it works I'll add it to the mongodb wrapper.
