### ISSUE TITLE
[strands_datacentre] MongoDB not working

### ISSUE THREAD

**Issue by ToMadoRe** [strands-project/strands_utils#25]
It is my first time using MongoDB. I have tried to get it working, however, I get the error message below. I am actually trying to get the waypoint patroller working but I cannot launch the "datacentre.launch" file without any issues.

'strands@werner:~/Projects$ rosrun strands_datacentre mongodb_server.py
[INFO] [WallTime: 1382622377.957277] Mongo server address: werner:62345
[INFO] [WallTime: 1382622377.970395] Found MongoDB version 2.0.4
[INFO] [WallTime: 1382622377.996608] Thu Oct 24 15:46:17 [initandlisten] MongoDB starting : pid=28420 port=62345 dbpath=/opt/strands/strands_datacentre 64-bit host=werner
[INFO] [WallTime: 1382622377.997160] Thu Oct 24 15:46:17 [initandlisten] db version v2.0.4, pdfile version 4.5
[INFO] [WallTime: 1382622377.997323] Thu Oct 24 15:46:17 [initandlisten] git version: nogitversion
[INFO] [WallTime: 1382622377.997491] Thu Oct 24 15:46:17 [initandlisten] build info: Linux lamiak 2.6.42-37-generic #58-Ubuntu SMP Thu Jan 24 15:28:10 UTC 2013 x86_64 BOOST_LIB_VERSION=1_46_1
[INFO] [WallTime: 1382622377.997666] Thu Oct 24 15:46:17 [initandlisten] options: { dbpath: "/opt/strands/strands_datacentre", port: 62345 }
[INFO] [WallTime: 1382622377.997904] Thu Oct 24 15:46:17 [initandlisten] exception in initAndListen: 10310 Unable to acquire lock for lockfilepath: /opt/strands/strands_datacentre/mongod.lock, terminating
[ERROR] [WallTime: 1382622377.998201] MongoDB process stopped!
[ERROR] [WallTime: 1382622377.998482] Mongo process error! Exit code=100
[INFO] [WallTime: 1382622377.999193] Shutting down datacentre
[WARN] [WallTime: 1382622377.999407] It looks like Mongo already died. Watch out as the DB might need recovery time at next run.
'

**Comment by nilsbore** [comment]
We also had this issue when we didn't give user permissions to write to /opt/strands/strands_datacentre. So that could be the problem.

**Comment by ToMadoRe** [comment]
Apparently some other process was blocking the /opt/strands/strands_datacentre/mongod.lock. Even though I had killed all other processes, it did not work. A reboot of the system did the job then. I could also start it today without problems. So I guess I can close this topic now - even though I don't really know the exact reason of the issue yesterday.
