### ISSUE TITLE
Datacenter taking up a lot of space on our disk

### ISSUE THREAD

**Issue by ghost** [strands-project/strands_utils#29]
We noticed that that datacenter is taking up about 8GB of space. I think we followed the initial setup suggestions and made a rather small partition for our stuff. While we have a 200GB partition that is close to empty, we are running out of space because of this. 

Is it possible to reconfigure where the datacenter is saving it's stuff? Or can you tell us which of the files we can safely delete in order to free up a bit of space again?

**Comment by cburbridge** [comment]
You can change where the db is stored by passing an argument to the launch file:

```
roslaunch strands_datacentre datacentre.launch db_path:=/my_alt_path
```

Did you split into a /home and a / partition?
How much space does you / partition have?

**Comment by ghost** [comment]
Cool good to know! I hope I didn't just forget to read the documentation.

We have a /localhome that is 200GB, a /opt/oldsystem for about 15GB and a /
partition of 20GB which is getting full now. (And then there are 4 more
rather small partitions) So I guess the solution is to store the stuff in
the /localhome/demo/my_mongodb_folder
