### ISSUE TITLE
[strands_tweets] Documentation incorrect

### ISSUE THREAD

**Issue by hawesie** [strands-project/strands_utils#35]
The strands_tweets documentation has some errors, notably:
- [x] The name of the node to run is incorrect
- [x] The instructions for Twitter authentication do not include instructions about setting the access mode to read-write (which was required for me).

**Comment by Jailander** [comment]
Hi,

I did the documentation before I did some changes, that is why the node names were wrong, now its fixed. 

About the instructions for setting read-write access the second bullet point under the starting out section says:
- Go to the settings tab and chage permitions to Read, Write and Access direct messages 

Or did you mean something different?

**Comment by Jailander** [comment]
By the way never name your python script the same as your package, that is why the documentation was wrong

**Comment by hawesie** [comment]
> Go to the settings tab and chage permitions to Read, Write and Access direct messages

For some reason I didn't covert this into the correct action, even when I re-read it. My apologies.

**Comment by Jailander** [comment]
That is fine, if you see something else let me know, however tomorrow I will add some more functionalities that I have been working on. And I will change the README.md again

**Comment by hawesie** [comment]
On 20 Nov 2013, at 23:23, Jaime Pulido Fentanes notifications@github.com wrote:

> That is fine, if you see something else let me know, however tomorrow I will add some more functionalities that I have been working on. And I will change the README.md again

What are you working on? I've been playing with some of this too, so I don't want to duplicate functionality. Can you create an issue so I know?

**Comment by Jailander** [comment]
I created a new issue for this

**Comment by hawesie** [comment]
Great, thanks.
