### ISSUE TITLE
[strands_marathon_achievements] marathon length

### ISSUE THREAD

**Issue by bfalacerda** [strands-project/strands_utils#43]
Just nitpicking about the README: a marathon is  42.195km, not 38.62. Just so we don't announce we completed an actual marathon beforehand

**Comment by hawesie** [comment]
Oops! Will fix later (unless someone does it first).

**Comment by bfalacerda** [comment]
I'll do it, just didn't want to do it without warning

**Comment by nilsbore** [comment]
In regards to that, shouldn't it be 42195 instead of 42.195? Could make for an even larger issue=).

**Comment by hawesie** [comment]
Yep, it's odd that I even managed to make that original mistake in there!

**Comment by bfalacerda** [comment]
yeah, it's corrected now. Three tries to get it right...
