### ISSUE TITLE
[robot_state_chain_publisher] linking error on hydro

### ISSUE THREAD

**Issue by bfalacerda** [strands-project/strands_utils#60]
When trying to compile this on hydro i get the following:

```
/usr/bin/ld: CMakeFiles/state_chain_publisher.dir/src/state_publisher.cpp.o: undefined reference to symbol 'KDL::Tree::Tree(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/bin/ld: note: 'KDL::Tree::Tree(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)' is defined in DSO /opt/ros/hydro/lib/liborocos-kdl.so.1.2 so try adding it to the linker command line
/opt/ros/hydro/lib/liborocos-kdl.so.1.2: could not read symbols: Invalid operation
collect2: ld returned 1 exit status
```

We were using this package because the original source was not catkinized, but now it is:

https://github.com/code-iai/robot_state_chain_publisher

Also, it looks like the linking errors are solved, so I think we should start using that.

**Comment by marc-hanheide** [comment]
so, can we just remove this package then?

**Comment by bfalacerda** [comment]
I'm not sure if it is being used. When I delete it, everything compiles, but I don't have anything running yet. The description of the package is:

  This package allows you to publish the state of a robot to the transform library topic. 
    In contrast to robot_state_publisher, it publishes the complete kinematic chain.

From what I understand, when we have the package in the workspace, the robot_state_publisher node that runs publishes the complete kinematic chain. If it's not in the system, the default robot_state_publisher node from ROS runs instead. Is someone using this complete kinematic chain? @kunzel told me he thinks it was added for the webserver stuff.

**Comment by bfalacerda** [comment]
closing, it looks like the package was removed meanwhile
